In [2]:
import numpy as np

class PositionalEncoding:
    
    def __init__(self, d_model=6, max_sequence_length=10):
        """
        d_model: dimension of model
        max_sequence_length: maximum number of tokens
        """
        self.d_model = d_model
        self.max_sequence_length = max_sequence_length
        
        # Create positional encoding once during initialization
        self.PE = self._create_positional_encoding()
    
    
    def _create_positional_encoding(self):
        """
        Creates positional encoding matrix of shape:
        (max_sequence_length, d_model)
        """
        
        position = np.arange(self.max_sequence_length)[:, np.newaxis]
        # (max_seq_len, 1)

        div_term = np.exp(
            np.arange(0, self.d_model, 2) * (-np.log(10000.0) / self.d_model)
        )
        # (d_model/2,)

        PE = np.zeros((self.max_sequence_length, self.d_model))

        PE[:, 0::2] = np.sin(position * div_term)
        PE[:, 1::2] = np.cos(position * div_term)

        return PE
    
    
    def forward(self):
        """
        Returns positional encoding matrix
        """
        return self.PE

In [3]:
pe = PositionalEncoding(d_model=6, max_sequence_length=10)

pos_encoding = pe.forward()

print("Positional Encoding shape:", pos_encoding.shape)
print(pos_encoding)

Positional Encoding shape: (10, 6)
[[ 0.          1.          0.          1.          0.          1.        ]
 [ 0.84147098  0.54030231  0.04639922  0.99892298  0.00215443  0.99999768]
 [ 0.90929743 -0.41614684  0.0926985   0.99569422  0.00430886  0.99999072]
 [ 0.14112001 -0.9899925   0.1387981   0.9903207   0.00646326  0.99997911]
 [-0.7568025  -0.65364362  0.18459872  0.98281398  0.00861763  0.99996287]
 [-0.95892427  0.28366219  0.23000171  0.97319022  0.01077197  0.99994198]
 [-0.2794155   0.96017029  0.27490927  0.96147017  0.01292625  0.99991645]
 [ 0.6569866   0.75390225  0.31922465  0.94767907  0.01508047  0.99988628]
 [ 0.98935825 -0.14550003  0.36285241  0.93184662  0.01723462  0.99985147]
 [ 0.41211849 -0.91113026  0.40569857  0.91400693  0.0193887   0.99981202]]
